### ISSUE TITLE
List of Assets not up to date, possibly due to fab.com-based acquisitions not being returned by the APIs

### ISSUE THREAD

**Issue by metaleap** [master-technology/AssetManagerStudio#50] opened 2024-10-23 17:29 UTC
Lookin' good, this app — but one weird thing I noticed: the list of assets it gives me is missing very recent additions when the official EGL over on my aged Windows box has its own list well up to date..

Doing the Refresh Assets menu action doesnt resolve this either.. so I wonder, maybe it's because those latest asset acquisitions I made only yesterday, so necessarily via fab.com — and you're connecting likely to established Epic marketplace (not fab) APIs that don't bother picking those up (and may be gone sooner or later)..

**Comment by NathanaelA** [comment] 2024-10-23 18:09
Looking into how the FAB api's work is on my todo list, I was hoping the backend API's would be the same, but if you got it via FAB and it isn't showing then there is obviously some differences...

**Comment by Micha95** [comment] 2024-11-16 22:21
i can actually confirm, that its not showing the assets purchased ( or even added for free) from fab.

**Comment by NathanaelA** [comment] 2024-12-06 00:39
You are correct I can confirm this and I do have support in progress (already documented API's to use) and got some things already coded.   But progress is slow since AMS is currently a fairly low priority do to trying to find a job (company downsized) and/or contract work -- those have higher priority...

**Comment by NathanaelA** [comment] 2024-12-09 06:20
Fab support has been released in v0.0.26.

**Closed as completed by NathanaelA** 2024-12-09 06:20 UTC
